### ISSUE TITLE
ブラウザが起動しなくなる

### ISSUE THREAD

**Issue by detsuku** [ElectronicObserverEN/ElectronicObserver#231]
本アプリを起動させてブラウザウインドウにゲーム画面が出るところ
たちどころにブラウザウインドウが真っ白になり
「ブラウザが起動していません クリックすると起動します」
というメッセージが表示されます。
クリックするとゲーム画面がでますが、また真っ白になりループとなります。
5.1.11にアップデートしてからこの現象が出るようになりました。

**Comment by myangelkamikaze** [comment]
Can you check if there's any details in windows event viewer?

![image](https://user-images.githubusercontent.com/40002167/186576556-e07f1d95-2a30-4a34-92e9-9158c1a7c028.png)

**Comment by detsuku** [comment]
There was this error event.
<img width="1280" alt="スクリーンショット 2022-08-27 010856" src="https://user-images.githubusercontent.com/77409739/186948261-f016cd8f-ab90-4add-9f41-f5c0c9839307.png">

Details
Application: EOBrowser.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: 無効なクラスです 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at BrowserLibCore.VolumeManager.GetCommandLine(String processName) in F:\ElectronicObserver\BrowserLibCore\VolumeManager.cs:line 118
   at BrowserLibCore.VolumeManager.GetVolumeObject(String processName, UInt32& processID, String proxySettings) in F:\ElectronicObserver\BrowserLibCore\VolumeManager.cs:line 146
   at BrowserLibCore.VolumeManager.CreateInstanceByProcessName(String processName, String proxySettings) in F:\ElectronicObserver\BrowserLibCore\VolumeManager.cs:line 178
   at Browser.BrowserViewModel.TryGetVolumeManager() in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 872
   at Browser.BrowserViewModel.ToolMenu_Other_Volume_ValueChanged() in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 1008
   at Browser.BrowserViewModel.<.ctor>b__132_3(Object sender, PropertyChangedEventArgs args) in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 169
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e)
   at Browser.BrowserViewModel.set_RealVolume(Int32 value) in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 110
   at Browser.BrowserViewModel.SetVolumeState() in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 903
   at Browser.BrowserViewModel.InitialAPIReceived() in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 618
   at MagicOnion.Client.DynamicClient.BrowserLibCore.IBrowserHostStreamingHubClient_afc6e7dd-af0d-40ca-a30b-20f3f04dade7.OnBroadcastEvent(Int32 , ArraySegment`1 )
   at MagicOnion.Client.StreamingHubClientBase`2.<>c__DisplayClass20_0.<StartSubscribe>b__1(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Browser.App.OnStartup(StartupEventArgs e) in F:\ElectronicObserver\Browser\App.xaml.cs:line 90
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Browser.App.Main()

**Comment by myangelkamikaze** [comment]
Hmm, that stack trace looks very odd. It looks like code from 5.1.10, but you noted that you're using 5.1.11.
Can you try downloading 5.1.11 again manually and see if it gets fixed?

**Comment by detsuku** [comment]
Was it a bad idea to overwrite 5.1.10?
I get the same event error when I download 5.1.11 and just extract it.

**Comment by myangelkamikaze** [comment]
No, overwriting is the normal way, auto update does that too.

Ah, sorry, I just noticed...
I made the new code after 5.1.11, not before...

I made a new preview release with the fix: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.1.12-preview2

**Comment by detsuku** [comment]
The browser window was still blank in 5.1.12-preview2.
However, the content of the event error had changed.

Details
Application: EOBrowser.exe
CoreCLR Version: 6.0.622.26707
.NET Version: 6.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Management.ManagementException: 無効なクラスです 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at BrowserLibCore.VolumeManager.<>c__DisplayClass7_0.<GetCommandLine>b__0() in F:\ElectronicObserver\BrowserLibCore\VolumeManager.cs:line 124
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()

**Comment by myangelkamikaze** [comment]
That's basically the same error.
Can you check this: https://stackoverflow.com/a/6930421

**Comment by detsuku** [comment]
Thank you.
The game screen now appears in the browser window.

**Comment by myangelkamikaze** [comment]
Alright.
Thanks for reporting.
