### ISSUE TITLE
EOが起動しない（異常終了）

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#284]
Version 5.2.0 を使用しています。
転居のためネットワーク環境が変わった影響か分かりませんが、
昨日まで正常に動作していたEOが、起動しなくなり（エラーメッセージなど無しに異常終了）
前提条件などどこからチェックすれば良いかアドバイスお願いします。

**Comment by myangelkamikaze** [comment]
Were you using version 5.2.0 before when it was still working, or an earlier version?
Are you using Windows 7 maybe?
If you are using Windows 7, then it's a known issue that was fixed in the latest preview: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.1-preview1

**Comment by Jack-of-spade** [comment]
Thank you for your prompt reply.
Sorry for the lack of information.
My operating system is Windows 10.
I also tried 5.2.1-preview1, but the situation did not change.

**Comment by myangelkamikaze** [comment]
You can reply in Japanese if that's easier for you.
Can you check if there's any error in the Windows event viewer? The one where the source is ".NET Runtime".
![image](https://user-images.githubusercontent.com/40002167/210072184-748b5c16-0631-423c-a32c-165ef5935ad1.png)

**Comment by Jack-of-spade** [comment]
アドバイスありがとうございます。
イベントビューアを確認したら'.NET Runtime'に関連して以下のエラーが発生していました。

ログの名前:         Application
ソース:           .NET Runtime
日付:            2022/12/30 5:16:17
イベント ID:       1026
タスクのカテゴリ:      なし
レベル:           エラー
キーワード:         クラシック
ユーザー:          N/A
コンピューター:       Dell
説明:
Application: ElectronicObserver.exe
CoreCLR Version: 6.0.922.41905
.NET Version: 6.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel, Boolean deferred)
   at System.Data.Common.DbConnection.BeginDbTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ElectronicObserver.Services.ApiFileService.ApiFileService.SaveApiData(String apiName, String requestBody, String responseBody) in F:\ElectronicObserver\ElectronicObserver\Services\ApiFileService\ApiFileService.cs:line 102
   at ElectronicObserver.Services.ApiFileService.ApiFileService.ProcessQueue() in F:\ElectronicObserver\ElectronicObserver\Services\ApiFileService\ApiFileService.cs:line 64
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by myangelkamikaze** [comment]
In the record folder, there should be a file named `ElectronicObserver.sqlite`. Can you upload that file here?
Deleting that file should fix your problem.

**Comment by Jack-of-spade** [comment]
ファイルを添付しました。確認お願いします。

[ElectronicObserver.zip](https://github.com/ElectronicObserverEN/ElectronicObserver/files/10326733/ElectronicObserver.zip)

**Comment by Jack-of-spade** [comment]
’ElectronicObserver.sqlite’を削除したら起動できました。
アドバイスありがとうございました。

**Comment by myangelkamikaze** [comment]
Alright.
We'll look into what happened with the sqlite file so that this can be avoided in the future.
