### ISSUE TITLE
ブラウザが起動できない問題

### ISSUE THREAD

**Issue by suikapple** [ElectronicObserverEN/ElectronicObserver#321]
こんにちは
もともと5.14バージョンを使用していました
5.23にアップデート（上書き）したら、下記のように「ブラウザが起動していません」になりました
クリックしても反応なしです
![image](https://user-images.githubusercontent.com/106939824/221472389-f14a56ba-253d-4288-be04-90bc8b455549.png)

**Comment by suikapple** [comment]
5.2以降は全部ブラウザ起動できないので、とりあえず5.1.13にダウングレードし、使っています

**Comment by myangelkamikaze** [comment]
Are there any errors in the log?
Can you try switching the browser to WebView2?

![image](https://user-images.githubusercontent.com/40002167/221538305-61de948c-4713-48aa-b663-3ec04c703629.png)

**Comment by suikapple** [comment]
おお、WebView2に変更したら、無事表示できました。
Thank you very much!

一応以下のエラーログが出ています
![image](https://user-images.githubusercontent.com/106939824/221572453-bd9afe97-27a7-4c09-b71e-439efd3cdef7.png)

**Comment by myangelkamikaze** [comment]
Might be the same problem as #326.
Do you have that setting enabled? If you live in Japan you should disable it, CefSharp should probably work again after that.
![image](https://user-images.githubusercontent.com/40002167/222461732-87185d38-8660-4eb4-915c-88098bc300d9.png)

**Comment by suikapple** [comment]
ガジェット・リダイレクトをもともとチェックが外されています。
やはりcefsharpは使えません
![image](https://user-images.githubusercontent.com/106939824/222761259-a4d2ace3-5e16-4182-b150-2c0f4fa0d2f3.png)

**Comment by myangelkamikaze** [comment]
Can you try downloading the latest version to a different location and try if it works? There was somebody with the same problem, and using a fresh version seemed to fix the problem.
We're still investigating what exactly the problem could be.

**Comment by suikapple** [comment]
最新の5.24をダウンロードしまして、別のドライブに入れて試しましたが、ブラウザを起動できないままです

**Comment by myangelkamikaze** [comment]
Can you try deleting `EOBrowser.deps.json` from the main folder?

**Comment by suikapple** [comment]
EOBrowser.deps.jsonを削除しましたが、起動できないままです

![image](https://user-images.githubusercontent.com/106939824/230731001-d3e7dd43-3b42-495a-8f62-0669b4d52c35.png)

**Comment by myangelkamikaze** [comment]
Can you check if there are any errors in the Windows event viewer?
![image](https://user-images.githubusercontent.com/40002167/230731179-952291c0-4f6d-474e-a599-5c6c2b8393e0.png)

**Comment by suikapple** [comment]
下記の2図のようにエラーが出ています

![image](https://user-images.githubusercontent.com/106939824/230916191-0cb145c2-e54f-4e0b-bb85-d43d929258b7.png)

Application: EOBrowser.exe
CoreCLR Version: 6.0.1423.7309
.NET Version: 6.0.14
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.Runtime, Version=109.1.110.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'. 指定されたファイルが見つかりません。
File name: 'CefSharp.Core.Runtime, Version=109.1.110.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'
   at CefSharp.Cef.EnableHighDPISupport()
   at Browser.CefSharpBrowser.CefSharpViewModel.InitializeAsync() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 77
   at Browser.BrowserViewModel.SetProxy(String proxy) in F:\ElectronicObserver\Browser\BrowserViewModel.cs:line 257
   at MagicOnion.Client.DynamicClient.BrowserLibCore.IBrowserHostStreamingHubClient_13a4fe9e-9bfe-459f-8ae8-dd41aaceeb4e.OnBroadcastEvent(Int32 , ArraySegment`1 )
   at MagicOnion.Client.StreamingHubClientBase`2.<>c__DisplayClass20_0.<StartSubscribe>b__1(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Browser.App.OnStartup(StartupEventArgs e) in F:\ElectronicObserver\Browser\App.xaml.cs:line 99
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Browser.App.Main()


![image](https://user-images.githubusercontent.com/106939824/230916351-643c5cc1-44c6-46bb-bdb8-37918563c867.png)
障害が発生しているアプリケーション名: EOBrowser.exe、バージョン: 5.2.5.0、タイム スタンプ: 0x63cf74d2
障害が発生しているモジュール名: KERNELBASE.dll、バージョン: 10.0.19041.2728、タイム スタンプ: 0xe7e53a4e
例外コード: 0xe0434352
障害オフセット: 0x000000000002cd29
障害が発生しているプロセス ID: 0x1bd4
障害が発生しているアプリケーションの開始時刻: 0x01d96bb43f8d4ce7
障害が発生しているアプリケーション パス: F:\Game\ElectronicObserver5.2.3EN\EOBrowser.exe
障害が発生しているモジュール パス: C:\Windows\System32\KERNELBASE.dll
レポート ID: b4f0c1bd-9a20-4b5b-8021-03cf8776c794
障害が発生しているパッケージの完全な名前: 
障害が発生しているパッケージに関連するアプリケーション ID:

**Comment by myangelkamikaze** [comment]
Yeah the first one is the reason. Can you check if there's a file named `CefSharp.Core.Runtime.dll` in `F:\Game\ElectronicObserver5.2.3EN`?
If that one is missing then it's possible an antivirus is deleting the file.

**Comment by suikapple** [comment]
CefSharp.Core.Runtime.dllは消えていないですね
下図のように

![image](https://user-images.githubusercontent.com/106939824/231767563-ac1d7d9a-9d98-428b-8fe4-34a351c29893.png)

**Comment by myangelkamikaze** [comment]
Is this still a problem?
