### ISSUE TITLE
The underlying frame is no longer valid 

### ISSUE THREAD

**Issue by THREETREETTT** [ElectronicObserverEN/ElectronicObserver#353]
I using the old version (5.1.12.0) is ok, but I can't use new version.
(My English is weak. I’m sorry.)

Error Report [ver. 5.2.6.0]: 2023/04/23 19:43:07
Error: Exception
System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_Url()
   at Browser.CefSharpBrowser.CefSharpViewModel.<>c.<GetGameFrame>b__23_1(IFrame f) in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 286
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Browser.CefSharpBrowser.CefSharpViewModel.GetGameFrame() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 286
   at Browser.CefSharpBrowser.CefSharpViewModel.ApplyStyleSheet() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 241
Additional info: Failed to apply stylesheet.
Stack trace:

**Comment by myangelkamikaze** [comment]
The easiest workaround is to switch to WebView2.
![image](https://user-images.githubusercontent.com/40002167/233840214-9786a4dd-8606-4fbd-afea-aa3de27c5176.png)

**Comment by THREETREETTT** [comment]
My problem is solved.
Thank you so much.

**Comment by myangelkamikaze** [comment]
CefSharp should work in the latest version too now.
