### ISSUE TITLE
[bug] Blank Screen or APIObserver: Failed to Start Observation

### ISSUE THREAD

**Issue by NaokiSato102** [ElectronicObserverEN/ElectronicObserver#410]
The screen remains blank, or only a window indicating a failure to prevent page refresh dialogue appears. I have tried clearing the cache, updating to a preview version, reloading multiple times, and reloading ignoring the cache, but the issue persists. What should I do next?

The log shows the following:
```
[2023/11/13 23:50:04][2] : 七四式電子観測儀 を起動しています…
[2023/11/13 23:50:04][2] : レコードをロードしました。
[2023/11/13 23:50:05][3] : APIObserver: Failed to start observation.Endpoint Titanium.Web.Proxy.Models.ExplicitProxyEndPoint failed to start. Check inner exception and exception data for details.
[2023/11/13 23:50:06][3] : 起動処理が完了しました。
[2023/11/13 23:50:09][3] : お使いのバージョンは最新です。
```

**Comment by myangelkamikaze** [comment]
Does using an older version work?

**Comment by NaokiSato102** [comment]
How old are we talking about? Is it version 5.2.10? I'm currently using 5.2.12-preview1.

**Comment by myangelkamikaze** [comment]
Well, any older release, really. But yeah, trying 5.2.10 first would be the best.

**Comment by NaokiSato102** [comment]
"I tried running version 5.2.11 to 5.2.8 directly without copying and pasting, but I encountered the same error. It doesn't seem to be an error caused by residual files in the root folder.

Before this issue occurred, I had an abnormal PC shutdown due to a tripped circuit breaker. Could this be related to the problem?

Additionally, I sometimes encounter this error as well:
```text
[2023/11/14 22:36:31][3] : スタイルシートの適用に失敗しました。 System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_Url()
   at Browser.CefSharpBrowser.CefSharpViewModel.<>c.<GetGameFrame>b__23_1(IFrame f) in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 291
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Browser.CefSharpBrowser.CefSharpViewModel.GetGameFrame() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 291
   at Browser.CefSharpBrowser.CefSharpViewModel.ApplyStyleSheet() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 248
```

**Comment by myangelkamikaze** [comment]
That error doesn't show up in the latest version right?

**Comment by myangelkamikaze** [comment]
Can you try [5.2.12-preview2](https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.12-preview2)? The log should give more useful info there.

**Comment by NaokiSato102** [comment]
```
[2023/11/15 22:26:52][3] : ConfigurationData: Settings\Configuration.xml does not exists.
[2023/11/15 22:26:55][2] : 七四式電子観測儀 を起動しています…
[2023/11/15 22:26:55][2] : Assets/Record/ShipParameterRecord.csv をコピーしました。
[2023/11/15 22:26:55][3] : レコードのロードに失敗しました。
[2023/11/15 22:26:55][2] : Assets/Settings/ShipGroups.xml をコピーしました。
[2023/11/15 22:26:55][3] : QuestProgressManager: Settings\QuestProgress.xml does not exists.
[2023/11/15 22:27:04][3] : APIObserver: Failed to start observation. アクセス許可で禁じられた方法でソケットにアクセスしようとしました。    at Titanium.Web.Proxy.ProxyServer.Listen(ProxyEndPoint endPoint)
   at Titanium.Web.Proxy.ProxyServer.Start(Boolean changeSystemProxySettings)
   at ElectronicObserver.Observer.APIObserver.Start(Int32 portID, Control uiControl) in F:\ElectronicObserver\ElectronicObserver\Observer\APIObserver.cs:line 781
[2023/11/15 22:27:05][3] : 起動処理が完了しました。
[2023/11/15 22:27:05][3] : お使いのバージョンは最新です。
[2023/11/15 22:27:06][3] : スタイルシートの適用に失敗しました。 System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_Url()
   at Browser.CefSharpBrowser.CefSharpViewModel.<>c.<GetGameFrame>b__23_1(IFrame f) in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 290
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Browser.CefSharpBrowser.CefSharpViewModel.GetGameFrame() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 290
   at Browser.CefSharpBrowser.CefSharpViewModel.ApplyStyleSheet() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 247
[2023/11/15 22:27:48][2] : 七四式電子観測儀 を終了しています…
[2023/11/15 22:27:49][2] : 終了処理が完了しました。

```

**Comment by myangelkamikaze** [comment]
Can you try running 七四式 as admin?

**Comment by NaokiSato102** [comment]
at Admin
```
[2023/11/15 23:14:39][3] : ConfigurationData: Settings\Configuration.xml does not exists.
[2023/11/15 23:14:41][2] : 七四式電子観測儀 を起動しています…
[2023/11/15 23:14:41][2] : Assets/Record/ShipParameterRecord.csv をコピーしました。
[2023/11/15 23:14:41][3] : レコードのロードに失敗しました。
[2023/11/15 23:14:41][2] : Assets/Settings/ShipGroups.xml をコピーしました。
[2023/11/15 23:14:42][3] : QuestProgressManager: Settings\QuestProgress.xml does not exists.
[2023/11/15 23:14:46][3] : APIObserver: Failed to start observation. アクセス許可で禁じられた方法でソケットにアクセスしようとしました。    at Titanium.Web.Proxy.ProxyServer.Listen(ProxyEndPoint endPoint)
   at Titanium.Web.Proxy.ProxyServer.Start(Boolean changeSystemProxySettings)
   at ElectronicObserver.Observer.APIObserver.Start(Int32 portID, Control uiControl) in F:\ElectronicObserver\ElectronicObserver\Observer\APIObserver.cs:line 781
[2023/11/15 23:14:47][3] : 起動処理が完了しました。
[2023/11/15 23:14:47][3] : お使いのバージョンは最新です。
[2023/11/15 23:14:49][3] : スタイルシートの適用に失敗しました。 System.Exception: The underlying frame is no longer valid - please check the IsValid property before calling!
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_Url()
   at Browser.CefSharpBrowser.CefSharpViewModel.<>c.<GetGameFrame>b__23_1(IFrame f) in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 290
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Browser.CefSharpBrowser.CefSharpViewModel.GetGameFrame() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 290
   at Browser.CefSharpBrowser.CefSharpViewModel.ApplyStyleSheet() in F:\ElectronicObserver\Browser\CefSharpBrowser\CefSharpViewModel.cs:line 247
[2023/11/15 23:14:58][2] : 七四式電子観測儀 を終了しています…
[2023/11/15 23:14:59][2] : 終了処理が完了しました。
```

**Comment by myangelkamikaze** [comment]
https://stackoverflow.com/a/67442253

**Comment by NaokiSato102** [comment]
It has been successfully resolved!
By the way, after being presented with this solution, I recalled that **Docker often leads to these kinds of silly problems**.
Perhaps it would be wise to advise caution regarding it?

**Comment by NaokiSato102** [comment]
Thank you for guiding me patiently to a resolution.
I am truly grateful.
My wife Haruna is also very pleased.

**Comment by myangelkamikaze** [comment]
I think a special warning for docker isn't needed. With the improved log, the error and solution are easily searchable on the internet.
You're welcome ・。・ｖ
