### ISSUE TITLE
Api file saving error: SQLite Error 11

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#414]
度々、以下のエラーメッセージが出るので対処方法を教えてください。

----------------------------------------------------------------
[2023/11/18 12:02:24][3] : Api file saving error: SQLite Error 11: 'database disk image is malformed'.    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ElectronicObserver.Services.ApiFileService.ApiFileService.SaveApiData(String apiName, String requestBody, String responseBody) in F:\ElectronicObserver\ElectronicObserver\Services\ApiFileService\ApiFileService.cs:line 115
   at ElectronicObserver.Services.ApiFileService.ApiFileService.SaveApiData(String apiName, String requestBody, String responseBody) in F:\ElectronicObserver\ElectronicObserver\Services\ApiFileService\ApiFileService.cs:line 115
   at ElectronicObserver.Services.ApiFileService.ApiFileService.ProcessApiDataAsync() in F:\ElectronicObserver\ElectronicObserver\Services\ApiFileService\ApiFileService.cs:line 70

**Comment by myangelkamikaze** [comment]
Renaming/deleting `ElectronicObserver.sqlite` in the `Record` folder and restarting 七四式 should fix it. If you can, upload the broken sqlite file somewhere so we can investigate what the problem could be.

**Comment by Jack-of-spade** [comment]
"ElectronicObserver.sqlite"をリネーム/削除すると"改修計画"に入力していた内容が消えますが、exportする方法はありますか？

**Comment by myangelkamikaze** [comment]
Yeah, that data is stored in there. If you can send us the `ElectronicObserver.sqlite` we can try to fix it. Or if you prefer to do it yourself, search the internet on how to restore an sqlite file.

**Comment by Jack-of-spade** [comment]
現在の"ElectronicObserver.sqlite"を添付します。
[ElectronicObserver.zip](https://github.com/ElectronicObserverEN/ElectronicObserver/files/13398987/ElectronicObserver.zip)

**Comment by myangelkamikaze** [comment]
[ElectronicObserver.zip](https://github.com/ElectronicObserverEN/ElectronicObserver/files/13399028/ElectronicObserver.zip) should be fixed.

**Comment by Jack-of-spade** [comment]
解決しました。
Thank you for your support.
