### ISSUE TITLE
出撃の任務が進捗しない

### ISSUE THREAD

**Issue by miwarin** [ElectronicObserverEN/ElectronicObserver#443]
# ElectronicObserver

ver. 5.3.3.0 - 2024/03/01 Release .NET 8.0.1

# 詳細

以下の任務を受諾した。

- Bd7: 南西諸島海域の制海権を握れ！
- Bq2: 戦果拡張任務！「Z作戦」前段作戦

その後 2-4 へ出撃し、ボスで S 勝利した。
しかし、上記 2 つの任務が進捗しない。(下記画像)

![スクリーンショット 2024-03-02 201540](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/250465/2372daf3-3558-4a43-a0ed-8b38fb876651)

ブラウザの任務欄では進捗していることを確認した。(下記画像) (2-4 と 6-4 を S 勝利済みなので「戦果拡張任務！「Z作戦」前段作戦」の進捗は 50% となっている)

![20240302_20161380](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/250465/13abffe8-0be1-4c6b-af01-511f135c1c02)

なお出撃記録 - 出撃データをコピー の結果は長文なので割愛する。

**Comment by myangelkamikaze** [comment]
Were there any errors in the log view when you got the S rank?

**Comment by miwarin** [comment]
> Were there any errors in the log view when you got the S rank?

uhhh. sorry. This problem occurred just before the version update.

and log:

```
[2024/03/02 20:02:22][2] : #1「6-3(2)」が「2-4 沖ノ島海域」へ出撃しました。
[2024/03/02 20:02:38][3] : Responseの受信中にエラーが発生しました。 The given key was not present in the dictionary.
[2024/03/02 20:03:27][2] : 2-4-B で「敵前衛巡洋艦戦隊」と交戦しました。( ランク: S, 提督Exp+120, 艦娘Exp+160 )
[2024/03/02 20:03:27][2] : 駆逐艦「陽炎」が戦列に加わりました。
[2024/03/02 20:03:27][3] : Responseの受信中にエラーが発生しました。 Object reference not set to an instance of an object.
[2024/03/02 20:03:50][2] : 2-4-G 開発資材 x 1
[2024/03/02 20:04:22][3] : Responseの受信中にエラーが発生しました。 The given key was not present in the dictionary.
[2024/03/02 20:05:22][2] : 2-4-L で「敵機動部隊 B群」と交戦しました。( ランク: A, 提督Exp+96, 艦娘Exp+250 )
[2024/03/02 20:05:22][2] : 駆逐艦「深雪」が戦列に加わりました。
[2024/03/02 20:05:22][3] : Responseの受信中にエラーが発生しました。 Object reference not set to an instance of an object.
[2024/03/02 20:06:03][3] : Responseの受信中にエラーが発生しました。 The given key was not present in the dictionary.
[2024/03/02 20:07:53][2] : 2-4-P で「敵侵攻中核水上打撃部隊」と交戦しました。( ランク: S, 提督Exp+1740, 艦娘Exp+420 )
[2024/03/02 20:07:53][2] : 駆逐艦「親潮」が戦列に加わりました。
[2024/03/02 20:07:53][3] : Responseの受信中にエラーが発生しました。 Object reference not set to an instance of an object.
[2024/03/02 20:08:17][2] : #1「6-3(2)」が帰投しました。
```

and error report:

```
Error Report [ver. 5.3.1.0]: 2024/03/02 20:07:53
Error: NullReferenceException
Object reference not set to an instance of an object.
Additional info: Responseの受信中にエラーが発生しました。
Stack trace:
   at ElectronicObserver.Data.Battle.BattleManager.<BattleFinished>g__IncrementSpecialAttack|87_0(BattleData bd) in F:\ElectronicObserver\ElectronicObserver\Data\Battle\BattleManager.cs:line 583
   at ElectronicObserver.Data.Battle.BattleManager.BattleFinished() in F:\ElectronicObserver\ElectronicObserver\Data\Battle\BattleManager.cs:line 599
   at ElectronicObserver.Observer.kcsapi.api_req_sortie.battleresult.OnResponseReceived(Object data) in F:\ElectronicObserver\ElectronicObserver\Observer\kcsapi\api_req_sortie\battleresult.cs:line 11
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at ElectronicObserver.Observer.APIDictionary.OnResponseReceived(String apiname, Object data) in F:\ElectronicObserver\ElectronicObserver\Observer\APIDictionary.cs:line 53
   at ElectronicObserver.Observer.APIObserver.LoadResponse(String path, String data) in F:\ElectronicObserver\ElectronicObserver\Observer\APIObserver.cs:line 1061

通信内容 : api_req_sortie/battleresult
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_ship_id":[1529,1529,1529,1555,1576,1576],"api_win_rank":"S","api_get_exp":1740,"api_mvp":1,"api_member_lv":120,"api_member_exp":105332305,"api_get_base_exp":420,"api_get_ship_exp":[-1,1512,504,504,504,504,504],"api_get_exp_lvup":[[2419401,2525000],[915520,1000000],[6204762,6320000],[5416511,5470000],[2456535,2525000],[4559323,4564000]],"api_dests":6,"api_destsf":1,"api_quest_name":"\u6c96\u30ce\u5cf6\u6d77\u57df","api_quest_level":6,"api_enemy_info":{"api_level":"","api_rank":"","api_deck_name":"\u6575\u4fb5\u653b\u4e2d\u6838\u6c34\u4e0a\u6253\u6483\u90e8\u968a"},"api_first_clear":0,"api_mapcell_incentive":0,"api_get_flag":[0,1,0],"api_get_ship":{"api_ship_id":456,"api_ship_type":"\u99c6\u9010\u8266","api_ship_name":"\u89aa\u6f6e","api_ship_getmes":"\u967d\u708e\u578b\u99c6\u9010\u8266\u56db\u756a\u8266\u3001\u89aa\u6f6e\u3067\u3059\u3002<br>\u53f8\u4ee4\u3001\u7b2c\u5341\u4e94\u99c6\u9010\u968a\u3001\u3069\u3046\u305e\u3088\u308d\u3057\u304f<br>\u3054\u6307\u5c0e\u304f\u3060\u3055\u3044\u3002\u304a\u9858\u3044\u3044\u305f\u3057\u307e\u3059\uff01"},"api_get_eventflag":0,"api_get_exmap_rate":0,"api_get_exmap_useitem_id":0,"api_escape_flag":0,"api_escape":null}}
```



ver. 5.3.3.0  does not occur. Additionally, the mission is progressing and is operating normally.

**Comment by myangelkamikaze** [comment]
Yeah, this error is expected for 5.3.1 and shouldn't happen anymore in 5.3.3.
