### ISSUE TITLE
グループ画面でのグループタブの全ロスト

### ISSUE THREAD

**Issue by ja1krg** [ElectronicObserverEN/ElectronicObserver#486]
一昨日、グループ画面にあった20個以上のグループタブが全て消え、「全所属艦」だけになりました。
その前後で、グループタブの追加や変更は行っていません。
不便なので、現在は新しくタブを追加して使っています。
アプリのバージョンはVer.5.3.6.0です。

**Comment by myangelkamikaze** [comment]
Is there any error in logs?
The most likely reason is that "Settings\ShipGroups.xml" got corrupted somehow.

**Comment by ja1krg** [comment]
The contents of the error log are pasted below.

Error Report [ver. 5.3.6.0]: 2024/07/22 19:12:44
Error: SerializationException
There was an error deserializing the object of type ElectronicObserver.Data.ShipGroupManager. Root element is missing.
Additional info:  Failed to load ShipGroupManager
Stack trace:
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at ElectronicObserver.Utility.Storage.DataStorage.Load(String path) in F:\ElectronicObserver\ElectronicObserver\Utility\Storage\DataStorage.cs:line 93

**Comment by myangelkamikaze** [comment]
Yeah, the file got corrupted somehow, so there's nothing we can do here.

**Comment by ja1krg** [comment]
Understood. I'm assuming my data won't come back...
That being said, if there is no way to recover it, and if this kind of trouble is occurring more or less, I think the app needs to process the backup. This is just a request.

**Comment by ja1krg** [comment]
This issue has occurred again. It has never happened before, but it has happened twice recently. Is it really just my environment's fault?

**Comment by myangelkamikaze** [comment]
Can you upload the ShipGroups.xml file?
Note that it'll be overridden when you close 七四式, so you need to make a copy before that.

**Comment by ja1krg** [comment]
I haven't closed the app yet. I can't send it as it is, so I'll edit the extension to txt and send it. By the way, the contents of this file look blank.

[ShipGroups.txt](https://github.com/user-attachments/files/16526189/ShipGroups.txt)

**Comment by myangelkamikaze** [comment]
I get this. Is that the content?
![image](https://github.com/user-attachments/assets/cf5bb2b3-1d5f-4f29-a97a-5d8a3b25a591)

**Comment by ja1krg** [comment]
No, it really is a zero byte file. For example in a hex editor it looks like this:

![スクリーンショット 2024-08-08 10 28 05](https://github.com/user-attachments/assets/52e3e100-e84d-428e-8420-b1504dc6b261)

**Comment by myangelkamikaze** [comment]
Hmm, maybe something happens when the file attempts to get saved. Can you check if there are any errors in the windows event viewer?
![unknown](https://github.com/user-attachments/assets/e619283f-b7ed-4fad-8996-e558634fd60f)

**Comment by ja1krg** [comment]
I checked the logs. There are several logs from the time in question, but none were from EOBrowser.exe. Instead, the security software and Nkdnssd Servive (?) were reporting errors.

![スクリーンショット 2024-08-08 16 02 47](https://github.com/user-attachments/assets/904eb0f8-4d45-4de2-8a5b-feaa214ad87d)

**Comment by myangelkamikaze** [comment]
That's from a different application.
Are you getting unexpected crashes or anything?
Can you check if your disk is okay?

I have no idea why that file would be getting corrupted if there weren't any unexpected crashes or something like that.

**Comment by KimidoriBoushi3** [comment]
同じ原因かどうかは不明ですが、今私も最新版にアップデートしたところ、グループが全消失したことを報告申し上げます。
